language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - addon-google_apis-google-24
