language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - addon-google_apis-google-26
script:
    ./gradlew build jacocoTestReport assembleAndroidTest
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 75dfc243-1ef7-4eaf-a6f0-b44f299584c8
